sudo: false
language: c

before_install:
  - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee -a /etc/apt/sources.list.d/pgdg.list
  - sudo apt-get update
  - sudo apt-get install -y postgresql-server-dev-9.6
  - eval "${MATRIX_EVAL}"

script:
  - true

after_failure:
  - .travis/cat_logs.sh

matrix:
  include:
    - env:
        - PG_VERSION=HEAD
      sudo: required
    - env:
        - PG_VERSION=HEAD
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      sudo: required
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          packages:
          - clang-5.0
    - env:
        - PG_VERSION=10
      sudo: required

# skip install script
install: true
